# Generated by Django 5.2.11 on 2026-03-02 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DROP_IN', 'Drop-in'), ('10_PACK', '10-Class Pack'), ('MONTHLY', 'Monthly Unlimited'), ('ANNUAL', 'Annual Unlimited')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(help_text='How many days the package lasts after purchase', verbose_name='Validity Period (Days)')),
                ('total_credits', models.IntegerField(default=0, help_text='Number of classes allowed. Set to 0 for unlimited packages.', verbose_name='Total Credits')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Is Unlimited?')),
                ('guest_passes', models.IntegerField(default=0, verbose_name='Guest Passes Included')),
            ],
            options={
                'verbose_name': 'Package Template',
                'verbose_name_plural': 'Package Templates',
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('credits_remaining', models.IntegerField(default=0, verbose_name='Credits Remaining')),
                ('guest_passes_remaining', models.IntegerField(default=0)),
                ('last_guest_pass_reset', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Active?')),
                ('package_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.packagetemplate', verbose_name='Base Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Package',
                'verbose_name_plural': 'User Packages',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('BOOKING', 'Booking'), ('CANCEL', 'Cancellation')], max_length=20)),
                ('amount_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credits_used', models.IntegerField(default=0)),
                ('guest_passes_used', models.IntegerField(default=0)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.userpackage')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='userpackage',
            constraint=models.CheckConstraint(condition=models.Q(('credits_remaining__gte', 0)), name='credits_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userpackage',
            constraint=models.CheckConstraint(condition=models.Q(('guest_passes_remaining__gte', 0)), name='guest_passes_non_negative'),
        ),
    ]
