# Generated by Django 5.2.11 on 2026-02-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DROP_IN', 'Drop-in'), ('10_PACK', '10-Class Pack'), ('MONTHLY', 'Monthly Unlimited'), ('ANNUAL', 'Annual Unlimited')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(help_text='How many days the package lasts after purchase', verbose_name='Validity Period (Days)')),
                ('total_credits', models.IntegerField(default=0, help_text='Number of classes allowed. Set to 0 for unlimited packages.', verbose_name='Total Credits')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Is Unlimited?')),
                ('guest_passes', models.IntegerField(default=0, verbose_name='Guest Passes Included')),
            ],
            options={
                'verbose_name': 'Package Template',
                'verbose_name_plural': 'Package Templates',
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('remaining_credits', models.IntegerField(verbose_name='Credits Remaining')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Active?')),
                ('package_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.packagetemplate', verbose_name='Base Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Package',
                'verbose_name_plural': 'User Packages',
            },
        ),
    ]
