# Generated by Django 5.2.11 on 2026-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetemplate',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
